export type RateItem = {
  id: string;
  category: string;
  subcategory: string;
  description: string;
  specification: string;
  unit: string;
  rate: number;
  rate_min: number;
  rate_max: number;
  gst_percent: number;
};

export const CATEGORIES = [
  'Civil Work',
  'Flooring',
  'Wall & Painting',
  'False Ceiling',
  'Electrical',
  'Plumbing',
  'Modular Kitchen',
  'Wardrobes & Storage',
  'Doors & Windows',
  'HVAC',
  'Furniture',
  'Décor & Soft Furnishing',
  'Staircase & Railing',
  'External Works',
  'Security Systems',
  'Fire Safety',
  'AV & Home Theater',
  'Gym & Wellness',
  'Solar & EV',
  'Landscaping',
  'Appliances',
  'Miscellaneous',
] as const;

export const UNITS = ['sqft', 'rft', 'nos', 'point', 'lot', 'rmt', 'kg', 'bag', 'set', 'cum', 'cft', 'lm', 'sqm', 'Wp'];

export const PROJECT_TYPES = [
  'Residential Apartment',
  'Residential Villa / Bungalow',
  'Penthouse',
  'Row House / Townhouse',
  'Commercial Office',
  'Retail / Showroom',
  'Hospitality / Hotel',
  'Restaurant / Café',
  'Healthcare / Clinic',
  'Educational Institution',
  'Industrial / Warehouse',
  'Mixed Use',
];

export const PRESET_SECTIONS = [
  'Living Room',
  'Dining Area',
  'Kitchen',
  'Master Bedroom',
  'Bedroom 2',
  'Bedroom 3',
  'Bedroom 4',
  'Master Bathroom',
  'Common Bathroom',
  'Powder Room',
  'Study / Home Office',
  'Balcony',
  'Entrance Lobby',
  'Foyer',
  'Staircase',
  'Terrace',
  'Puja Room',
  'Store Room',
  'Servant Room / Utility',
  'Garage / Parking',
  'External Façade',
  'Common Areas',
  'Gym / Fitness Room',
  'Home Theater',
  'Bar / Entertainment Area',
  'Swimming Pool Area',
  'Landscape / Garden',
  'Basement',
  'Attic / Loft',
  'Conference Room',
  'Reception Area',
];

export const RATE_LIBRARY: RateItem[] = [
  // ─── CIVIL WORK ───────────────────────────────────────────────
  { id: 'c01', category: 'Civil Work', subcategory: 'Demolition', description: 'Demolition of existing brick wall', specification: 'Including debris removal off site', unit: 'sqft', rate: 30, rate_min: 20, rate_max: 45, gst_percent: 18 },
  { id: 'c02', category: 'Civil Work', subcategory: 'Demolition', description: 'Tile / flooring removal', specification: 'Including chipping and disposal', unit: 'sqft', rate: 18, rate_min: 12, rate_max: 25, gst_percent: 18 },
  { id: 'c03', category: 'Civil Work', subcategory: 'Masonry', description: 'Brick partition wall 4" thick', specification: 'First class brick, CM 1:6', unit: 'sqft', rate: 105, rate_min: 85, rate_max: 130, gst_percent: 18 },
  { id: 'c04', category: 'Civil Work', subcategory: 'Masonry', description: 'Brick partition wall 9" thick', specification: 'First class brick, CM 1:6', unit: 'sqft', rate: 165, rate_min: 140, rate_max: 200, gst_percent: 18 },
  { id: 'c05', category: 'Civil Work', subcategory: 'Masonry', description: 'AAC block partition wall 4" thick', specification: 'Autoclaved aerated concrete block, block mortar', unit: 'sqft', rate: 95, rate_min: 75, rate_max: 125, gst_percent: 18 },
  { id: 'c06', category: 'Civil Work', subcategory: 'Plastering', description: 'Internal wall plaster 12mm', specification: '2-coat plaster CM 1:4', unit: 'sqft', rate: 35, rate_min: 25, rate_max: 48, gst_percent: 18 },
  { id: 'c07', category: 'Civil Work', subcategory: 'Plastering', description: 'External wall plaster 20mm', specification: 'CM 1:4 with integral waterproofing admixture', unit: 'sqft', rate: 48, rate_min: 35, rate_max: 65, gst_percent: 18 },
  { id: 'c08', category: 'Civil Work', subcategory: 'Plastering', description: 'Gypsum plaster (internal walls)', specification: 'Machine-applied gypsum plaster 12mm, smooth finish', unit: 'sqft', rate: 42, rate_min: 32, rate_max: 58, gst_percent: 18 },
  { id: 'c09', category: 'Civil Work', subcategory: 'Waterproofing', description: 'Bathroom waterproofing', specification: 'Dr. Fixit / Fosroc 2-coat system, 1.5mm DFT', unit: 'sqft', rate: 85, rate_min: 65, rate_max: 120, gst_percent: 18 },
  { id: 'c10', category: 'Civil Work', subcategory: 'Waterproofing', description: 'Terrace waterproofing', specification: 'Bituminous membrane 4mm APP/SBS, torch applied', unit: 'sqft', rate: 130, rate_min: 100, rate_max: 180, gst_percent: 18 },
  { id: 'c11', category: 'Civil Work', subcategory: 'Waterproofing', description: 'Basement waterproofing', specification: 'Crystalline waterproofing coating (Xypex/Kryton)', unit: 'sqft', rate: 160, rate_min: 120, rate_max: 220, gst_percent: 18 },
  { id: 'c12', category: 'Civil Work', subcategory: 'Flooring base', description: 'PCC flooring base', specification: 'M15 concrete 75mm thick, tamped finish', unit: 'sqft', rate: 48, rate_min: 35, rate_max: 65, gst_percent: 18 },
  { id: 'c13', category: 'Civil Work', subcategory: 'Flooring base', description: 'Screed for floor levelling', specification: 'CM 1:4 self-levelling screed 40mm', unit: 'sqft', rate: 32, rate_min: 22, rate_max: 45, gst_percent: 18 },
  { id: 'c14', category: 'Civil Work', subcategory: 'Partition', description: 'Gypsum board partition 75mm', specification: '12.5mm GBD both sides, GI framing, L&T/Saint-Gobain', unit: 'sqft', rate: 125, rate_min: 95, rate_max: 160, gst_percent: 18 },
  { id: 'c15', category: 'Civil Work', subcategory: 'Partition', description: 'Gypsum board partition 100mm (acoustic)', specification: '15mm GBD both sides, mineral wool insulation', unit: 'sqft', rate: 195, rate_min: 150, rate_max: 260, gst_percent: 18 },
  { id: 'c16', category: 'Civil Work', subcategory: 'RCC Work', description: 'RCC slab M25 (100mm)', specification: 'Ready-mix M25, TMT rebar, formwork', unit: 'sqft', rate: 380, rate_min: 280, rate_max: 520, gst_percent: 18 },
  { id: 'c17', category: 'Civil Work', subcategory: 'RCC Work', description: 'RCC column (per bag cement)', specification: 'M25 with 12mm+ TMT rebar, formwork, curing', unit: 'bag', rate: 1800, rate_min: 1400, rate_max: 2500, gst_percent: 18 },

  // ─── FLOORING ─────────────────────────────────────────────────
  { id: 'f01', category: 'Flooring', subcategory: 'Tiles', description: 'Vitrified tile laying 600×600mm', specification: 'Supply & fix, CM 1:4 bed, epoxy grout', unit: 'sqft', rate: 75, rate_min: 60, rate_max: 95, gst_percent: 18 },
  { id: 'f02', category: 'Flooring', subcategory: 'Tiles', description: 'Vitrified tile laying 800×800mm', specification: 'Supply & fix, CM 1:4 bed, epoxy grout', unit: 'sqft', rate: 85, rate_min: 65, rate_max: 110, gst_percent: 18 },
  { id: 'f03', category: 'Flooring', subcategory: 'Tiles', description: 'Large format tile 1200×600mm (GVT)', specification: 'Supply & fix, polymer adhesive, no grout joint', unit: 'sqft', rate: 110, rate_min: 85, rate_max: 150, gst_percent: 18 },
  { id: 'f04', category: 'Flooring', subcategory: 'Tiles', description: 'Anti-skid ceramic tile bathroom 300×300mm', specification: 'Supply & fix, epoxy grout, PVA bonding', unit: 'sqft', rate: 70, rate_min: 55, rate_max: 90, gst_percent: 18 },
  { id: 'f05', category: 'Flooring', subcategory: 'Marble', description: 'Indian marble flooring Makrana white', specification: 'Supply & fix, 18mm, machine polished', unit: 'sqft', rate: 160, rate_min: 120, rate_max: 220, gst_percent: 18 },
  { id: 'f06', category: 'Flooring', subcategory: 'Marble', description: 'Italian marble flooring Statuario', specification: 'Supply & fix, 18mm, mirror finish, diamond cut', unit: 'sqft', rate: 380, rate_min: 280, rate_max: 550, gst_percent: 18 },
  { id: 'f07', category: 'Flooring', subcategory: 'Marble', description: 'Onyx marble flooring (premium)', specification: 'Supply & fix, 15mm, backlit optional', unit: 'sqft', rate: 600, rate_min: 400, rate_max: 950, gst_percent: 18 },
  { id: 'f08', category: 'Flooring', subcategory: 'Wood', description: 'Engineered wood flooring 12mm HDF', specification: 'Supply & fix, click lock, foam underlay', unit: 'sqft', rate: 280, rate_min: 200, rate_max: 400, gst_percent: 18 },
  { id: 'f09', category: 'Flooring', subcategory: 'Wood', description: 'Solid teak wood flooring 18mm', specification: 'Supply & fix, tongue-groove, lacquer finish', unit: 'sqft', rate: 550, rate_min: 400, rate_max: 750, gst_percent: 18 },
  { id: 'f10', category: 'Flooring', subcategory: 'Wood', description: 'Bamboo flooring', specification: 'Horizontal grain, carbonised, click lock, 14mm', unit: 'sqft', rate: 220, rate_min: 160, rate_max: 320, gst_percent: 18 },
  { id: 'f11', category: 'Flooring', subcategory: 'Vinyl', description: 'LVT vinyl plank flooring (SPC)', specification: 'Supply & fix, 5mm SPC core, rigid, click lock', unit: 'sqft', rate: 130, rate_min: 95, rate_max: 180, gst_percent: 18 },
  { id: 'f12', category: 'Flooring', subcategory: 'Vinyl', description: 'Vinyl sheet flooring 2mm', specification: 'Commercial grade Tarkett/Armstrong, adhesive fixed', unit: 'sqft', rate: 95, rate_min: 70, rate_max: 130, gst_percent: 18 },
  { id: 'f13', category: 'Flooring', subcategory: 'Stone', description: 'Kotah stone flooring 20mm honed', specification: 'Supply & fix, machine cut', unit: 'sqft', rate: 105, rate_min: 80, rate_max: 140, gst_percent: 18 },
  { id: 'f14', category: 'Flooring', subcategory: 'Stone', description: 'Granite flooring black / tan brown', specification: 'Supply & fix, 18mm, polished', unit: 'sqft', rate: 145, rate_min: 110, rate_max: 195, gst_percent: 18 },
  { id: 'f15', category: 'Flooring', subcategory: 'Epoxy', description: 'Epoxy self-levelling flooring 3mm', specification: '2-part epoxy, gloss/matt finish', unit: 'sqft', rate: 185, rate_min: 140, rate_max: 260, gst_percent: 18 },
  { id: 'f16', category: 'Flooring', subcategory: 'Epoxy', description: 'Micro-cement / micro-topping 3mm', specification: 'Trowel-applied, 2 coats colour + sealer', unit: 'sqft', rate: 320, rate_min: 240, rate_max: 450, gst_percent: 18 },
  { id: 'f17', category: 'Flooring', subcategory: 'Carpet', description: 'Broadloom carpet wall to wall', specification: 'Nylon/wool, 32oz, adhesive fixed with underlay', unit: 'sqft', rate: 180, rate_min: 120, rate_max: 280, gst_percent: 5 },
  { id: 'f18', category: 'Flooring', subcategory: 'Carpet', description: 'Modular carpet tiles 500×500mm', specification: 'Commercial grade, bitumen backing, loose lay', unit: 'sqft', rate: 150, rate_min: 100, rate_max: 240, gst_percent: 5 },
  { id: 'f19', category: 'Flooring', subcategory: 'Rubber', description: 'Rubber flooring (gym / play)', specification: 'SBR rubber tile 10mm, bevelled edge', unit: 'sqft', rate: 160, rate_min: 110, rate_max: 220, gst_percent: 18 },

  // ─── WALL & PAINTING ──────────────────────────────────────────
  { id: 'p01', category: 'Wall & Painting', subcategory: 'Preparation', description: 'Wall putty 2 coats', specification: 'Asian Paints / Berger wall putty, sanded smooth', unit: 'sqft', rate: 22, rate_min: 16, rate_max: 30, gst_percent: 18 },
  { id: 'p02', category: 'Wall & Painting', subcategory: 'Preparation', description: 'Primer coat', specification: 'Asian Paints/Dulux interior primer', unit: 'sqft', rate: 12, rate_min: 8, rate_max: 18, gst_percent: 18 },
  { id: 'p03', category: 'Wall & Painting', subcategory: 'Interior', description: 'Interior emulsion 2 coats', specification: 'Asian Paints Tractor Emulsion / Dulux Velvet Touch', unit: 'sqft', rate: 28, rate_min: 20, rate_max: 40, gst_percent: 18 },
  { id: 'p04', category: 'Wall & Painting', subcategory: 'Interior', description: 'Premium interior emulsion 2 coats', specification: 'Asian Paints Royale Matt / Dulux AquaClean', unit: 'sqft', rate: 42, rate_min: 32, rate_max: 58, gst_percent: 18 },
  { id: 'p05', category: 'Wall & Painting', subcategory: 'Texture', description: 'Interior texture paint (1 design)', specification: 'Royale Play / Berger Illusions applied texture', unit: 'sqft', rate: 90, rate_min: 55, rate_max: 160, gst_percent: 18 },
  { id: 'p06', category: 'Wall & Painting', subcategory: 'Texture', description: 'Venetian plaster / lime wash finish', specification: 'Multi-coat application, waxed finish', unit: 'sqft', rate: 280, rate_min: 200, rate_max: 420, gst_percent: 18 },
  { id: 'p07', category: 'Wall & Painting', subcategory: 'Exterior', description: 'Exterior emulsion 2 coats', specification: 'Asian Paints Apex / Dulux Weathershield', unit: 'sqft', rate: 45, rate_min: 35, rate_max: 62, gst_percent: 18 },
  { id: 'p08', category: 'Wall & Painting', subcategory: 'Wood', description: 'Enamel paint on woodwork 2 coats', specification: 'Asian Paints Apcolite enamel, primer + 2 coats', unit: 'sqft', rate: 38, rate_min: 28, rate_max: 52, gst_percent: 18 },
  { id: 'p09', category: 'Wall & Painting', subcategory: 'Wood', description: 'PU polish on woodwork (gloss / matt)', specification: 'Glossy PU 3 coats / Matt PU 2 coats + lacquer', unit: 'sqft', rate: 65, rate_min: 48, rate_max: 90, gst_percent: 18 },
  { id: 'p10', category: 'Wall & Painting', subcategory: 'Metal', description: 'Enamel paint on MS / iron works', specification: 'Red oxide primer + 2 enamel coats', unit: 'sqft', rate: 35, rate_min: 25, rate_max: 48, gst_percent: 18 },
  { id: 'p11', category: 'Wall & Painting', subcategory: 'Wallpaper', description: 'Wallpaper supply & installation', specification: 'Non-woven, sticker/paste type, standard patterns', unit: 'sqft', rate: 120, rate_min: 80, rate_max: 200, gst_percent: 18 },
  { id: 'p12', category: 'Wall & Painting', subcategory: 'Wallpaper', description: 'Imported designer wallpaper', specification: 'Phillip Jeffries / Elitis, paste-the-wall', unit: 'sqft', rate: 350, rate_min: 200, rate_max: 600, gst_percent: 18 },
  { id: 'p13', category: 'Wall & Painting', subcategory: 'Cladding', description: 'Stone veneer wall cladding (ledger)', specification: 'Natural ledger stone 20–25mm, adhesive fixed', unit: 'sqft', rate: 480, rate_min: 350, rate_max: 700, gst_percent: 18 },
  { id: 'p14', category: 'Wall & Painting', subcategory: 'Cladding', description: 'Wooden wall panelling (veneer)', specification: '18mm plywood base + veneer finish, lacquer', unit: 'sqft', rate: 650, rate_min: 480, rate_max: 950, gst_percent: 18 },
  { id: 'p15', category: 'Wall & Painting', subcategory: 'Cladding', description: 'Fluted wood panel wall cladding', specification: 'Solid MDF fluted panels, natural oak/walnut finish', unit: 'sqft', rate: 850, rate_min: 620, rate_max: 1200, gst_percent: 18 },
  { id: 'p16', category: 'Wall & Painting', subcategory: 'Cladding', description: 'Aluminium composite panel (ACP) cladding', specification: '4mm ACP Alucobond/Viva, powder-coat finish', unit: 'sqft', rate: 220, rate_min: 160, rate_max: 320, gst_percent: 18 },
  { id: 'p17', category: 'Wall & Painting', subcategory: 'Cladding', description: 'Tile wall cladding (bathroom/kitchen)', specification: 'Ceramic/vitrified 300×600mm, epoxy grout, CM 1:3', unit: 'sqft', rate: 65, rate_min: 50, rate_max: 90, gst_percent: 18 },

  // ─── FALSE CEILING ────────────────────────────────────────────
  { id: 'fc01', category: 'False Ceiling', subcategory: 'Gypsum', description: 'Gypsum false ceiling plain', specification: '12.5mm GBD, GI framing, L&T/Saint-Gobain', unit: 'sqft', rate: 90, rate_min: 70, rate_max: 120, gst_percent: 18 },
  { id: 'fc02', category: 'False Ceiling', subcategory: 'Gypsum', description: 'Gypsum false ceiling with cove', specification: '12.5mm GBD, cove for indirect lighting', unit: 'sqft', rate: 125, rate_min: 95, rate_max: 165, gst_percent: 18 },
  { id: 'fc03', category: 'False Ceiling', subcategory: 'Gypsum', description: 'Gypsum moisture-resistant (MR) ceiling', specification: '12.5mm MR board, wet areas', unit: 'sqft', rate: 115, rate_min: 88, rate_max: 150, gst_percent: 18 },
  { id: 'fc04', category: 'False Ceiling', subcategory: 'POP', description: 'POP false ceiling plain', specification: '10mm POP on GI frame, smooth finish', unit: 'sqft', rate: 78, rate_min: 60, rate_max: 100, gst_percent: 18 },
  { id: 'fc05', category: 'False Ceiling', subcategory: 'POP', description: 'POP cornice / border moulding', specification: 'POP decorative cornice 4" wide, painted', unit: 'rft', rate: 85, rate_min: 60, rate_max: 120, gst_percent: 18 },
  { id: 'fc06', category: 'False Ceiling', subcategory: 'Wood', description: 'Wooden baffle ceiling', specification: 'Solid MDF baffles 120mm×40mm, oak veneer', unit: 'sqft', rate: 420, rate_min: 300, rate_max: 600, gst_percent: 18 },
  { id: 'fc07', category: 'False Ceiling', subcategory: 'Metal', description: 'Metal strip / linear ceiling', specification: 'Aluminium linear 84C profile, powder coated', unit: 'sqft', rate: 280, rate_min: 200, rate_max: 400, gst_percent: 18 },
  { id: 'fc08', category: 'False Ceiling', subcategory: 'Metal', description: 'Perforated aluminium ceiling panel', specification: 'Aluminium tile 600×600mm, perforated, snap-lock', unit: 'sqft', rate: 350, rate_min: 250, rate_max: 500, gst_percent: 18 },
  { id: 'fc09', category: 'False Ceiling', subcategory: 'Stretch', description: 'Stretch ceiling system (PVC)', specification: 'BARRISOL/CLIPSO PVC membrane, translucent or opaque', unit: 'sqft', rate: 350, rate_min: 250, rate_max: 500, gst_percent: 18 },
  { id: 'fc10', category: 'False Ceiling', subcategory: 'Provision', description: 'Cove lighting channel (L-angle)', specification: 'GI L-angle cove, min 150mm depth, LED provision', unit: 'rft', rate: 380, rate_min: 280, rate_max: 520, gst_percent: 18 },

  // ─── ELECTRICAL ──────────────────────────────────────────────
  { id: 'e01', category: 'Electrical', subcategory: 'Wiring', description: 'Concealed wiring per point (light/fan)', specification: 'Havells / Polycab FR 1.5sqmm copper, conduit', unit: 'point', rate: 1200, rate_min: 950, rate_max: 1600, gst_percent: 18 },
  { id: 'e02', category: 'Electrical', subcategory: 'Wiring', description: 'Concealed wiring per point (power/AC)', specification: 'Havells / Polycab FR 4sqmm copper, conduit', unit: 'point', rate: 1800, rate_min: 1400, rate_max: 2400, gst_percent: 18 },
  { id: 'e03', category: 'Electrical', subcategory: 'Wiring', description: 'Data / LAN point (Cat 6)', specification: 'Cat 6 UTP, RJ45 jack, structured cabling', unit: 'point', rate: 2200, rate_min: 1600, rate_max: 3200, gst_percent: 18 },
  { id: 'e04', category: 'Electrical', subcategory: 'DB', description: 'Distribution board 4-way (TPN)', specification: 'Schneider/L&T TPN DB, 4 MCB slots', unit: 'nos', rate: 5500, rate_min: 4000, rate_max: 8000, gst_percent: 18 },
  { id: 'e05', category: 'Electrical', subcategory: 'DB', description: 'Distribution board 8-way (TPN)', specification: 'Schneider/L&T TPN DB, 8 MCB slots', unit: 'nos', rate: 9000, rate_min: 7000, rate_max: 13000, gst_percent: 18 },
  { id: 'e06', category: 'Electrical', subcategory: 'DB', description: 'MCB single pole 10/16A', specification: 'Schneider/ABB/L&T, C-curve', unit: 'nos', rate: 500, rate_min: 350, rate_max: 750, gst_percent: 18 },
  { id: 'e07', category: 'Electrical', subcategory: 'Switches', description: 'Switch plate (Anchor Roma) 1M', specification: '1 module switch plate, 6A/16A socket', unit: 'nos', rate: 750, rate_min: 500, rate_max: 1100, gst_percent: 18 },
  { id: 'e08', category: 'Electrical', subcategory: 'Switches', description: 'Switch plate (Legrand Arteor) 1M', specification: '1 module Legrand plate with switch', unit: 'nos', rate: 2800, rate_min: 1800, rate_max: 4200, gst_percent: 18 },
  { id: 'e09', category: 'Electrical', subcategory: 'Switches', description: 'Smart touch switch plate', specification: 'Havells Reeva / Legrand Mosaic touch switch', unit: 'nos', rate: 4500, rate_min: 3000, rate_max: 7500, gst_percent: 18 },
  { id: 'e10', category: 'Electrical', subcategory: 'Switches', description: 'USB charger socket (Type A + C)', specification: 'Legrand/Anchor, 5V/3A dual USB, 1M plate', unit: 'nos', rate: 1800, rate_min: 1200, rate_max: 2800, gst_percent: 18 },
  { id: 'e11', category: 'Electrical', subcategory: 'Lighting', description: 'Recessed LED panel light 12W', specification: 'Havells/Crompton 12W round/square panel', unit: 'nos', rate: 1200, rate_min: 800, rate_max: 1800, gst_percent: 18 },
  { id: 'e12', category: 'Electrical', subcategory: 'Lighting', description: 'Recessed spotlight / downlight 7W', specification: 'Philips/Havells GU10 MR16 LED downlight', unit: 'nos', rate: 950, rate_min: 600, rate_max: 1500, gst_percent: 18 },
  { id: 'e13', category: 'Electrical', subcategory: 'Lighting', description: 'LED strip light cove (per rft)', specification: 'Philips/Havells 12W/m WW/NW, dimmer point', unit: 'rft', rate: 280, rate_min: 180, rate_max: 420, gst_percent: 18 },
  { id: 'e14', category: 'Electrical', subcategory: 'Lighting', description: 'Pendant light point provision', specification: 'Wiring point + canopy bracket for pendant', unit: 'nos', rate: 2200, rate_min: 1600, rate_max: 3200, gst_percent: 18 },
  { id: 'e15', category: 'Electrical', subcategory: 'Lighting', description: 'Outdoor weatherproof wall light (IP65)', specification: 'IP65 supply & install, wall mounted', unit: 'nos', rate: 2800, rate_min: 1800, rate_max: 4500, gst_percent: 18 },
  { id: 'e16', category: 'Electrical', subcategory: 'Lighting', description: 'Dimmer module for lights', specification: 'Legrand/Schneider trailing-edge dimmer, 250W', unit: 'nos', rate: 3500, rate_min: 2200, rate_max: 5500, gst_percent: 18 },
  { id: 'e17', category: 'Electrical', subcategory: 'Safety', description: 'ELCB / RCD 25A 30mA', specification: 'Schneider/Legrand RCCB for bathroom circuit', unit: 'nos', rate: 2200, rate_min: 1600, rate_max: 3200, gst_percent: 18 },
  { id: 'e18', category: 'Electrical', subcategory: 'Safety', description: 'Surge protection device (SPD)', specification: 'DIN rail SPD, 40kA for main DB', unit: 'nos', rate: 5500, rate_min: 3800, rate_max: 8500, gst_percent: 18 },

  // ─── PLUMBING ─────────────────────────────────────────────────
  { id: 'pl01', category: 'Plumbing', subcategory: 'Piping', description: 'CPVC pipe 3/4" concealed', specification: 'Astral/Supreme CPVC, hot + cold supply', unit: 'rft', rate: 230, rate_min: 170, rate_max: 310, gst_percent: 18 },
  { id: 'pl02', category: 'Plumbing', subcategory: 'Piping', description: 'uPVC soil/drain pipe 4" SWR', specification: 'Supreme/Prince uPVC SWR pipe, 110mm', unit: 'rft', rate: 280, rate_min: 200, rate_max: 380, gst_percent: 18 },
  { id: 'pl03', category: 'Plumbing', subcategory: 'Piping', description: 'PEX pipe 15mm concealed', specification: 'Hepvo / Wavin PEX-A, 15mm flexible, clip-on', unit: 'rft', rate: 190, rate_min: 140, rate_max: 260, gst_percent: 18 },
  { id: 'pl04', category: 'Plumbing', subcategory: 'Sanitary', description: 'Wall-hung WC with concealed cistern', specification: 'Jaquar/Parryware WC + Jaquar Inwall cistern', unit: 'nos', rate: 28000, rate_min: 18000, rate_max: 55000, gst_percent: 18 },
  { id: 'pl05', category: 'Plumbing', subcategory: 'Sanitary', description: 'EWC (floor-mounted WC) close-coupled', specification: 'Jaquar/Kohler standard close-coupled, soft-close seat', unit: 'nos', rate: 14000, rate_min: 9000, rate_max: 28000, gst_percent: 18 },
  { id: 'pl06', category: 'Plumbing', subcategory: 'Sanitary', description: 'Counter basin with mixer tap', specification: 'Jaquar/Kohler counter basin + single lever mixer', unit: 'nos', rate: 16000, rate_min: 10000, rate_max: 35000, gst_percent: 18 },
  { id: 'pl07', category: 'Plumbing', subcategory: 'Sanitary', description: 'Pedestal wash basin with tap', specification: 'Jaquar/Parryware pedestal basin + pillar tap', unit: 'nos', rate: 9500, rate_min: 6500, rate_max: 18000, gst_percent: 18 },
  { id: 'pl08', category: 'Plumbing', subcategory: 'Sanitary', description: 'Health faucet set (bidet spray)', specification: 'Jaquar/Grohe health faucet + holder + hose', unit: 'nos', rate: 1800, rate_min: 1200, rate_max: 3200, gst_percent: 18 },
  { id: 'pl09', category: 'Plumbing', subcategory: 'Shower', description: 'Overhead rain shower 250mm', specification: 'Jaquar/Kohler overhead shower head, CP finish', unit: 'nos', rate: 8500, rate_min: 5500, rate_max: 18000, gst_percent: 18 },
  { id: 'pl10', category: 'Plumbing', subcategory: 'Shower', description: 'Concealed thermostatic shower system', specification: 'Grohe Grohtherm / Jaquar concealed valve + head + arm', unit: 'nos', rate: 32000, rate_min: 22000, rate_max: 65000, gst_percent: 18 },
  { id: 'pl11', category: 'Plumbing', subcategory: 'Shower', description: 'Shower enclosure frameless 8mm', specification: 'Frameless tempered glass, pivot door, chrome hardware', unit: 'nos', rate: 22000, rate_min: 15000, rate_max: 45000, gst_percent: 18 },
  { id: 'pl12', category: 'Plumbing', subcategory: 'Water heating', description: 'Storage water heater 15L BEE 5-star', specification: 'Racold/Havells Adonia 15L', unit: 'nos', rate: 14000, rate_min: 9000, rate_max: 22000, gst_percent: 18 },
  { id: 'pl13', category: 'Plumbing', subcategory: 'Water heating', description: 'Storage water heater 25L BEE 5-star', specification: 'Racold/Havells 25L', unit: 'nos', rate: 18000, rate_min: 12000, rate_max: 28000, gst_percent: 18 },
  { id: 'pl14', category: 'Plumbing', subcategory: 'Accessories', description: 'CP bathroom accessories set', specification: 'Jaquar/Grohe: towel ring, soap dish, TP holder, hook', unit: 'set', rate: 8500, rate_min: 5000, rate_max: 20000, gst_percent: 18 },
  { id: 'pl15', category: 'Plumbing', subcategory: 'Accessories', description: 'Floor drain anti-smell (CP)', specification: 'Jaquar/Kohler anti-smell floor drain 100×100mm', unit: 'nos', rate: 1200, rate_min: 800, rate_max: 2200, gst_percent: 18 },
  { id: 'pl16', category: 'Plumbing', subcategory: 'Treatment', description: 'RO + UV water purifier (under-sink)', specification: 'Kent/Pureit RO+UV 10L/hr, under-counter, auto TDS', unit: 'nos', rate: 22000, rate_min: 14000, rate_max: 38000, gst_percent: 18 },
  { id: 'pl17', category: 'Plumbing', subcategory: 'Treatment', description: 'Water softener (residential)', specification: 'Pentair/Kent 50 LPH, resin, automatic brine regen', unit: 'nos', rate: 45000, rate_min: 30000, rate_max: 80000, gst_percent: 18 },

  // ─── MODULAR KITCHEN ──────────────────────────────────────────
  { id: 'mk01', category: 'Modular Kitchen', subcategory: 'Cabinets', description: 'Base cabinet with shutter & hardware', specification: '18mm BWP ply, acrylic/membrane shutter, soft close', unit: 'sqft', rate: 3800, rate_min: 2800, rate_max: 5500, gst_percent: 18 },
  { id: 'mk02', category: 'Modular Kitchen', subcategory: 'Cabinets', description: 'Wall cabinet with shutter & hardware', specification: '18mm BWP ply, acrylic shutter, soft close hinge', unit: 'sqft', rate: 3000, rate_min: 2200, rate_max: 4500, gst_percent: 18 },
  { id: 'mk03', category: 'Modular Kitchen', subcategory: 'Cabinets', description: 'Loft / overhead cabinet', specification: '18mm BWP ply, laminate/paint shutter', unit: 'sqft', rate: 2200, rate_min: 1600, rate_max: 3200, gst_percent: 18 },
  { id: 'mk04', category: 'Modular Kitchen', subcategory: 'Cabinets', description: 'Tall pantry unit with pull-out shelves', specification: '18mm BWP ply, Hettich pull-outs, full height', unit: 'sqft', rate: 4500, rate_min: 3200, rate_max: 6500, gst_percent: 18 },
  { id: 'mk05', category: 'Modular Kitchen', subcategory: 'Countertop', description: 'Granite countertop supply & fix', specification: 'Min 20mm, polished, bullnose edge treatment', unit: 'sqft', rate: 380, rate_min: 250, rate_max: 600, gst_percent: 18 },
  { id: 'mk06', category: 'Modular Kitchen', subcategory: 'Countertop', description: 'Quartz countertop supply & fix', specification: 'Silestone/Caesarstone 20mm, undermount edge', unit: 'sqft', rate: 750, rate_min: 550, rate_max: 1100, gst_percent: 18 },
  { id: 'mk07', category: 'Modular Kitchen', subcategory: 'Countertop', description: 'SS countertop 16 gauge', specification: 'SS 304, 16 gauge, 50mm nosing, welded', unit: 'sqft', rate: 550, rate_min: 400, rate_max: 750, gst_percent: 18 },
  { id: 'mk08', category: 'Modular Kitchen', subcategory: 'Appliances point', description: 'SS sink double bowl supply & fix', specification: 'Carysil/Franke SS 304 double bowl, waste fittings', unit: 'nos', rate: 9500, rate_min: 6000, rate_max: 18000, gst_percent: 18 },
  { id: 'mk09', category: 'Modular Kitchen', subcategory: 'Appliances point', description: 'Kitchen chimney 60cm baffle filter', specification: 'Faber/Elica 60cm, 1200m³/h, touch control', unit: 'nos', rate: 14000, rate_min: 8000, rate_max: 28000, gst_percent: 18 },
  { id: 'mk10', category: 'Modular Kitchen', subcategory: 'Appliances point', description: 'Kitchen chimney 90cm baffle filter', specification: 'Faber/Elica 90cm, 1400m³/h, auto-clean', unit: 'nos', rate: 20000, rate_min: 12000, rate_max: 38000, gst_percent: 18 },
  { id: 'mk11', category: 'Modular Kitchen', subcategory: 'Accessories', description: 'Hettich/Hafele kitchen accessories lot', specification: 'Bottle pull-out + waste bin + drawer inserts', unit: 'lot', rate: 18000, rate_min: 12000, rate_max: 28000, gst_percent: 18 },
  { id: 'mk12', category: 'Modular Kitchen', subcategory: 'Accessories', description: 'Corner solution (magic corner / carousel)', specification: 'Hettich/Hafele corner pull-out or carousel', unit: 'nos', rate: 14000, rate_min: 9000, rate_max: 22000, gst_percent: 18 },

  // ─── WARDROBES & STORAGE ──────────────────────────────────────
  { id: 'w01', category: 'Wardrobes & Storage', subcategory: 'Sliding', description: 'Sliding wardrobe with mirror', specification: '18mm BWP ply, Godrej/Hettich slider, 2 mirror doors', unit: 'sqft', rate: 4200, rate_min: 3200, rate_max: 6000, gst_percent: 18 },
  { id: 'w02', category: 'Wardrobes & Storage', subcategory: 'Hinged', description: 'Hinged wardrobe with internal fittings', specification: '18mm BWP ply, laminate finish, Hettich hinges', unit: 'sqft', rate: 3500, rate_min: 2600, rate_max: 5000, gst_percent: 18 },
  { id: 'w03', category: 'Wardrobes & Storage', subcategory: 'Walk-in', description: 'Walk-in wardrobe system', specification: '18mm BWP ply, open shelving + rods + drawers', unit: 'sqft', rate: 5500, rate_min: 4000, rate_max: 8500, gst_percent: 18 },
  { id: 'w04', category: 'Wardrobes & Storage', subcategory: 'TV Unit', description: 'TV unit with wall display', specification: '18mm BWP ply, mix open/closed, back panel, veneer', unit: 'sqft', rate: 3800, rate_min: 2800, rate_max: 5500, gst_percent: 18 },
  { id: 'w05', category: 'Wardrobes & Storage', subcategory: 'TV Unit', description: 'Floating media console (wall-hung)', specification: '18mm ply, wall-hung, concealed LED provision', unit: 'sqft', rate: 4500, rate_min: 3200, rate_max: 6500, gst_percent: 18 },
  { id: 'w06', category: 'Wardrobes & Storage', subcategory: 'Shoe rack', description: 'Shoe rack cabinet with ventilated shutters', specification: '18mm ply, slanted shelves, perforated doors', unit: 'sqft', rate: 2800, rate_min: 2000, rate_max: 4000, gst_percent: 18 },
  { id: 'w07', category: 'Wardrobes & Storage', subcategory: 'Crockery', description: 'Crockery / display unit with LED', specification: '18mm ply + glass shutter, laminate, LED strip inside', unit: 'sqft', rate: 4000, rate_min: 3000, rate_max: 5800, gst_percent: 18 },
  { id: 'w08', category: 'Wardrobes & Storage', subcategory: 'Study', description: 'Study table with overhead cabinet', specification: '18mm ply, L-shaped, 2 drawers, overhead shutter', unit: 'nos', rate: 28000, rate_min: 18000, rate_max: 45000, gst_percent: 18 },
  { id: 'w09', category: 'Wardrobes & Storage', subcategory: 'Puja', description: 'Puja unit / mandir cabinet', specification: '18mm ply, jali door, internal marble/teak, LED', unit: 'nos', rate: 35000, rate_min: 22000, rate_max: 65000, gst_percent: 18 },
  { id: 'w10', category: 'Wardrobes & Storage', subcategory: 'Bar', description: 'Bar unit / drinks cabinet', specification: '18mm ply, glass shelves, LED, bottle racks', unit: 'sqft', rate: 5000, rate_min: 3500, rate_max: 8000, gst_percent: 18 },

  // ─── DOORS & WINDOWS ──────────────────────────────────────────
  { id: 'd01', category: 'Doors & Windows', subcategory: 'Doors', description: 'Teak wood door frame + panel shutter', specification: '2nd teak, 5-panel shutter, M-seal, PU lacquer', unit: 'nos', rate: 48000, rate_min: 32000, rate_max: 85000, gst_percent: 18 },
  { id: 'd02', category: 'Doors & Windows', subcategory: 'Doors', description: 'Flush door with architrave (solid core)', specification: 'Solid core flush 35mm, laminate finish, SS hardware', unit: 'nos', rate: 14000, rate_min: 9000, rate_max: 22000, gst_percent: 18 },
  { id: 'd03', category: 'Doors & Windows', subcategory: 'Doors', description: 'WPC door frame + shutter', specification: 'Virgo/Royal Touch WPC, termite-proof, paint finish', unit: 'nos', rate: 20000, rate_min: 14000, rate_max: 32000, gst_percent: 18 },
  { id: 'd04', category: 'Doors & Windows', subcategory: 'Doors', description: 'Frameless glass door 12mm (floor spring)', specification: 'Tempered glass, patch fittings, SS floor spring', unit: 'nos', rate: 35000, rate_min: 25000, rate_max: 60000, gst_percent: 18 },
  { id: 'd05', category: 'Doors & Windows', subcategory: 'Doors', description: 'Sliding glass door (patio / balcony)', specification: 'uPVC or Al frame, 6mm toughened glass, 2-track', unit: 'sqft', rate: 1100, rate_min: 800, rate_max: 1600, gst_percent: 18 },
  { id: 'd06', category: 'Doors & Windows', subcategory: 'Hardware', description: 'Door hardware set (mortise lock + handle)', specification: 'Dorset/Hafele mortise lock + lever handle per door', unit: 'nos', rate: 4500, rate_min: 2800, rate_max: 9500, gst_percent: 18 },
  { id: 'd07', category: 'Doors & Windows', subcategory: 'Windows', description: 'uPVC window (fixed + sliding 2-track)', specification: 'Prominance/Veka uPVC, 5mm tinted glass, mesh', unit: 'sqft', rate: 950, rate_min: 700, rate_max: 1300, gst_percent: 18 },
  { id: 'd08', category: 'Doors & Windows', subcategory: 'Windows', description: 'Aluminium powder-coated window', specification: 'Hindalco section, 5mm glass, bronze/silver finish', unit: 'sqft', rate: 650, rate_min: 480, rate_max: 900, gst_percent: 18 },
  { id: 'd09', category: 'Doors & Windows', subcategory: 'Windows', description: 'Double-glazed uPVC window (DGU)', specification: '70mm uPVC profile, 4+12+4mm DGU, argon-filled', unit: 'sqft', rate: 1600, rate_min: 1200, rate_max: 2200, gst_percent: 18 },
  { id: 'd10', category: 'Doors & Windows', subcategory: 'Partitions', description: 'Frameless glass partition 12mm tempered', specification: 'Tempered glass, patch fittings, patch hardware', unit: 'sqft', rate: 700, rate_min: 520, rate_max: 950, gst_percent: 18 },
  { id: 'd11', category: 'Doors & Windows', subcategory: 'Partitions', description: 'Aluminium framed glass partition', specification: 'Al section, 8mm tempered glass, powder coated', unit: 'sqft', rate: 480, rate_min: 350, rate_max: 650, gst_percent: 18 },
  { id: 'd12', category: 'Doors & Windows', subcategory: 'Skylights', description: 'Polycarbonate skylight / rooflight', specification: '16mm multi-wall PC, Al frame, fixed', unit: 'sqft', rate: 750, rate_min: 550, rate_max: 1100, gst_percent: 18 },

  // ─── HVAC ─────────────────────────────────────────────────────
  { id: 'h01', category: 'HVAC', subcategory: 'Split AC', description: 'Split AC 1-ton supply & install', specification: 'Daikin/Mitsubishi 3-star inverter, copper piping 3m', unit: 'nos', rate: 36000, rate_min: 28000, rate_max: 50000, gst_percent: 28 },
  { id: 'h02', category: 'HVAC', subcategory: 'Split AC', description: 'Split AC 1.5-ton supply & install', specification: 'Daikin/Mitsubishi 5-star inverter, copper piping 3m', unit: 'nos', rate: 48000, rate_min: 36000, rate_max: 68000, gst_percent: 28 },
  { id: 'h03', category: 'HVAC', subcategory: 'Split AC', description: 'Split AC 2-ton supply & install', specification: 'Daikin/Hitachi 5-star inverter, copper piping 3m', unit: 'nos', rate: 62000, rate_min: 48000, rate_max: 88000, gst_percent: 28 },
  { id: 'h04', category: 'HVAC', subcategory: 'Cassette AC', description: '4-way cassette AC 1.5-ton', specification: 'Daikin/Mitsubishi VRF cassette, concealed in ceiling', unit: 'nos', rate: 75000, rate_min: 55000, rate_max: 110000, gst_percent: 28 },
  { id: 'h05', category: 'HVAC', subcategory: 'Ducted', description: 'Ducted AC system (per ton)', specification: 'Daikin ducted AHU, insulated GI ductwork, diffusers', unit: 'nos', rate: 85000, rate_min: 65000, rate_max: 130000, gst_percent: 28 },
  { id: 'h06', category: 'HVAC', subcategory: 'Ventilation', description: 'Exhaust fan kitchen 200mm', specification: 'Havells/Usha 8" exhaust fan, ducted to shaft', unit: 'nos', rate: 5500, rate_min: 3500, rate_max: 9000, gst_percent: 18 },
  { id: 'h07', category: 'HVAC', subcategory: 'Ventilation', description: 'Bathroom exhaust fan 150mm', specification: 'Havells/Usha 6" noise <35dB, humidity sensor opt.', unit: 'nos', rate: 3800, rate_min: 2500, rate_max: 6000, gst_percent: 18 },
  { id: 'h08', category: 'HVAC', subcategory: 'Ventilation', description: 'Energy recovery ventilator (ERV)', specification: 'Panasonic/Mitsubishi ERV, 150CMH, ducted', unit: 'nos', rate: 55000, rate_min: 40000, rate_max: 85000, gst_percent: 18 },

  // ─── FURNITURE ───────────────────────────────────────────────
  { id: 'fur01', category: 'Furniture', subcategory: 'Seating', description: 'Sofa 3-seater custom fabric', specification: 'Teak frame, foam seating 40D, fabric upholstery', unit: 'nos', rate: 52000, rate_min: 35000, rate_max: 90000, gst_percent: 18 },
  { id: 'fur02', category: 'Furniture', subcategory: 'Seating', description: 'Sofa 2-seater custom fabric', specification: 'Teak frame, foam seating, fabric upholstery', unit: 'nos', rate: 38000, rate_min: 25000, rate_max: 65000, gst_percent: 18 },
  { id: 'fur03', category: 'Furniture', subcategory: 'Seating', description: 'Accent / lounge chair', specification: 'Custom upholstered, hardwood frame, castors optional', unit: 'nos', rate: 22000, rate_min: 14000, rate_max: 45000, gst_percent: 18 },
  { id: 'fur04', category: 'Furniture', subcategory: 'Seating', description: 'Ottoman / pouf', specification: 'Custom upholstered, solid base, fabric/leather cover', unit: 'nos', rate: 10000, rate_min: 6000, rate_max: 22000, gst_percent: 18 },
  { id: 'fur05', category: 'Furniture', subcategory: 'Beds', description: 'Bed frame king-size (6×6.5ft)', specification: 'Solid wood/PLY frame, upholstered headboard, box base', unit: 'nos', rate: 42000, rate_min: 28000, rate_max: 75000, gst_percent: 18 },
  { id: 'fur06', category: 'Furniture', subcategory: 'Beds', description: 'Bed frame queen-size (5×6.5ft)', specification: 'Solid wood/PLY frame, upholstered headboard', unit: 'nos', rate: 32000, rate_min: 22000, rate_max: 58000, gst_percent: 18 },
  { id: 'fur07', category: 'Furniture', subcategory: 'Dining', description: 'Dining table 6-seater', specification: 'Solid sheesham / marble top, 72"×36"', unit: 'nos', rate: 35000, rate_min: 22000, rate_max: 65000, gst_percent: 18 },
  { id: 'fur08', category: 'Furniture', subcategory: 'Dining', description: 'Dining chair (per piece)', specification: 'Solid wood frame, fabric/leatherette seat', unit: 'nos', rate: 7500, rate_min: 4500, rate_max: 18000, gst_percent: 18 },
  { id: 'fur09', category: 'Furniture', subcategory: 'Tables', description: 'Coffee / center table', specification: 'Marble/glass top, metal base or solid wood', unit: 'nos', rate: 18000, rate_min: 10000, rate_max: 38000, gst_percent: 18 },
  { id: 'fur10', category: 'Furniture', subcategory: 'Tables', description: 'Console / side table', specification: 'Solid wood or metal frame with MDF top', unit: 'nos', rate: 12000, rate_min: 7000, rate_max: 25000, gst_percent: 18 },
  { id: 'fur11', category: 'Furniture', subcategory: 'Outdoor', description: 'Outdoor patio furniture set', specification: 'WPC/teak 4-seater table + chairs, weather-resistant', unit: 'set', rate: 45000, rate_min: 28000, rate_max: 80000, gst_percent: 18 },
  { id: 'fur12', category: 'Furniture', subcategory: 'Office', description: 'Executive office desk (L-shape)', specification: '18mm ply, laminate finish, cable management grommet', unit: 'nos', rate: 32000, rate_min: 20000, rate_max: 55000, gst_percent: 18 },
  { id: 'fur13', category: 'Furniture', subcategory: 'Office', description: 'Office chair (ergonomic)', specification: 'Mesh back, lumbar support, armrests, height adjust', unit: 'nos', rate: 12000, rate_min: 7000, rate_max: 28000, gst_percent: 18 },

  // ─── DÉCOR & SOFT FURNISHING ──────────────────────────────────
  { id: 'dec01', category: 'Décor & Soft Furnishing', subcategory: 'Curtains', description: 'Curtains (sheer + blackout pair)', specification: 'Supply & stitch, eyelet header, track included', unit: 'sqft', rate: 380, rate_min: 250, rate_max: 600, gst_percent: 5 },
  { id: 'dec02', category: 'Décor & Soft Furnishing', subcategory: 'Blinds', description: 'Roller blind (blackout)', specification: 'Manual roller, custom cut, cassette system', unit: 'sqft', rate: 320, rate_min: 220, rate_max: 480, gst_percent: 5 },
  { id: 'dec03', category: 'Décor & Soft Furnishing', subcategory: 'Blinds', description: 'Venetian blind (aluminium 25mm)', specification: '25mm slats, cord operated, custom width', unit: 'sqft', rate: 380, rate_min: 280, rate_max: 520, gst_percent: 5 },
  { id: 'dec04', category: 'Décor & Soft Furnishing', subcategory: 'Blinds', description: 'Motorised roller blind (Somfy RTS)', specification: 'Somfy RTS motor, remote + app control', unit: 'sqft', rate: 750, rate_min: 550, rate_max: 1100, gst_percent: 18 },
  { id: 'dec05', category: 'Décor & Soft Furnishing', subcategory: 'Carpet', description: 'Area rug custom (hand-tufted)', specification: 'Hand-tufted / machine-made, custom size', unit: 'sqft', rate: 250, rate_min: 150, rate_max: 500, gst_percent: 5 },
  { id: 'dec06', category: 'Décor & Soft Furnishing', subcategory: 'Mirrors', description: 'Decorative framed mirror', specification: 'Custom frame, silver/bronze, wall-hung', unit: 'nos', rate: 8500, rate_min: 4500, rate_max: 22000, gst_percent: 18 },
  { id: 'dec07', category: 'Décor & Soft Furnishing', subcategory: 'Art', description: 'Canvas artwork / wall art', specification: 'Locally sourced contemporary canvas, framed', unit: 'nos', rate: 12000, rate_min: 6000, rate_max: 40000, gst_percent: 12 },
  { id: 'dec08', category: 'Décor & Soft Furnishing', subcategory: 'Plants', description: 'Indoor plant with decorative pot (large)', specification: 'Fiddle leaf / areca palm / monstera, decorative pot', unit: 'nos', rate: 5500, rate_min: 3000, rate_max: 12000, gst_percent: 0 },
  { id: 'dec09', category: 'Décor & Soft Furnishing', subcategory: 'Plants', description: 'Vertical garden wall (living wall)', specification: 'GI frame, planting pockets, drip irrigation, 10 plant types', unit: 'sqft', rate: 1800, rate_min: 1200, rate_max: 3000, gst_percent: 0 },

  // ─── STAIRCASE & RAILING ──────────────────────────────────────
  { id: 'st01', category: 'Staircase & Railing', subcategory: 'Treads', description: 'Granite stair tread (per step)', specification: 'Granite 800×300×30mm, nosing chamfered, polish', unit: 'nos', rate: 2800, rate_min: 2000, rate_max: 4500, gst_percent: 18 },
  { id: 'st02', category: 'Staircase & Railing', subcategory: 'Treads', description: 'Wooden stair tread (per step)', specification: 'Teak / walnut 40mm solid, lacquer finish', unit: 'nos', rate: 4200, rate_min: 3000, rate_max: 7000, gst_percent: 18 },
  { id: 'st03', category: 'Staircase & Railing', subcategory: 'Treads', description: 'Marble stair tread (per step)', specification: 'Statuario/Carrara 20mm, machine polished, nosing', unit: 'nos', rate: 3500, rate_min: 2500, rate_max: 6000, gst_percent: 18 },
  { id: 'st04', category: 'Staircase & Railing', subcategory: 'Railing', description: 'SS railing (round tube 50mm)', specification: 'SS 316 handrail + balusters, satin finish', unit: 'rft', rate: 2800, rate_min: 2000, rate_max: 4500, gst_percent: 18 },
  { id: 'st05', category: 'Staircase & Railing', subcategory: 'Railing', description: 'MS railing (flat bar design)', specification: 'MS powder-coated, custom design', unit: 'rft', rate: 2000, rate_min: 1400, rate_max: 3200, gst_percent: 18 },
  { id: 'st06', category: 'Staircase & Railing', subcategory: 'Railing', description: 'Glass railing 12mm frameless', specification: 'Tempered glass, SS top handrail, patch fittings', unit: 'rft', rate: 4200, rate_min: 3000, rate_max: 6500, gst_percent: 18 },
  { id: 'st07', category: 'Staircase & Railing', subcategory: 'Railing', description: 'Wooden handrail (teak)', specification: 'Teak handrail 75×50mm, lacquer, wall brackets', unit: 'rft', rate: 1400, rate_min: 900, rate_max: 2200, gst_percent: 18 },

  // ─── EXTERNAL WORKS ───────────────────────────────────────────
  { id: 'ext01', category: 'External Works', subcategory: 'Compound', description: 'Compound wall (brick, plastered)', specification: '230mm brick wall, CM 1:4, plaster both sides', unit: 'sqft', rate: 280, rate_min: 200, rate_max: 380, gst_percent: 18 },
  { id: 'ext02', category: 'External Works', subcategory: 'Paving', description: 'Paver block driveway 60mm', specification: 'Interlocking 60mm paver, GSB base, sand bed', unit: 'sqft', rate: 95, rate_min: 70, rate_max: 130, gst_percent: 18 },
  { id: 'ext03', category: 'External Works', subcategory: 'Paving', description: 'Natural stone paved pathway', specification: 'Kota/sandstone 30mm natural, sand bed', unit: 'sqft', rate: 145, rate_min: 100, rate_max: 200, gst_percent: 18 },
  { id: 'ext04', category: 'External Works', subcategory: 'Gate', description: 'MS main gate (sliding) 14ft', specification: 'MS sliding gate, powder coated, automation optional', unit: 'nos', rate: 65000, rate_min: 40000, rate_max: 120000, gst_percent: 18 },
  { id: 'ext05', category: 'External Works', subcategory: 'Pool', description: 'Swimming pool (8×4m plunge)', specification: 'RCC shell, waterproofed tile, filtration, variable pump', unit: 'lot', rate: 850000, rate_min: 600000, rate_max: 1500000, gst_percent: 18 },
  { id: 'ext06', category: 'External Works', subcategory: 'Pool', description: 'Pool coping & surrounding', specification: 'Natural stone coping, surround tiles', unit: 'rft', rate: 3800, rate_min: 2800, rate_max: 5500, gst_percent: 18 },
  { id: 'ext07', category: 'External Works', subcategory: 'Façade', description: 'External wall texture coating', specification: 'Asian Paints Apex Ultima / textured finish, 2 coats', unit: 'sqft', rate: 55, rate_min: 40, rate_max: 78, gst_percent: 18 },

  // ─── SECURITY SYSTEMS ────────────────────────────────────────
  { id: 'sec01', category: 'Security Systems', subcategory: 'CCTV', description: 'CCTV 4-camera system (HD)', specification: 'Hikvision/CP Plus 2MP Turbo HD, DVR 8ch, 1TB HDD', unit: 'lot', rate: 28000, rate_min: 18000, rate_max: 45000, gst_percent: 18 },
  { id: 'sec02', category: 'Security Systems', subcategory: 'CCTV', description: 'CCTV 8-camera system (HD)', specification: 'Hikvision 2MP IP cameras, NVR 16ch, 2TB HDD, 24" monitor', unit: 'lot', rate: 55000, rate_min: 38000, rate_max: 90000, gst_percent: 18 },
  { id: 'sec03', category: 'Security Systems', subcategory: 'CCTV', description: 'IP PTZ camera (outdoor)', specification: '4MP PTZ, 30x optical zoom, IR 200m, PoE', unit: 'nos', rate: 28000, rate_min: 18000, rate_max: 48000, gst_percent: 18 },
  { id: 'sec04', category: 'Security Systems', subcategory: 'Access Control', description: 'Biometric access control (door)', specification: 'Fingerprint + card reader, 12V electric lock, controller', unit: 'nos', rate: 18000, rate_min: 12000, rate_max: 32000, gst_percent: 18 },
  { id: 'sec05', category: 'Security Systems', subcategory: 'Access Control', description: 'Smart door lock (digital)', specification: 'Eufy/Yale fingerprint + PIN + app + key, deadbolt', unit: 'nos', rate: 16000, rate_min: 10000, rate_max: 28000, gst_percent: 18 },
  { id: 'sec06', category: 'Security Systems', subcategory: 'Video Intercom', description: 'Video door phone (colour 7")', specification: 'Legrand/Urmet 2-wire, colour 7" monitor, night vision', unit: 'nos', rate: 16000, rate_min: 10000, rate_max: 28000, gst_percent: 18 },
  { id: 'sec07', category: 'Security Systems', subcategory: 'Alarm', description: 'Burglar alarm system (4 zones)', specification: 'Honeywell Vista 20P, door/window sensors, PIR, siren', unit: 'lot', rate: 32000, rate_min: 22000, rate_max: 55000, gst_percent: 18 },
  { id: 'sec08', category: 'Security Systems', subcategory: 'Alarm', description: 'Motion sensor (PIR) with alarm', specification: 'Honeywell/Bosch PIR, 12m 90°, wireless/wired', unit: 'nos', rate: 4500, rate_min: 2800, rate_max: 8000, gst_percent: 18 },
  { id: 'sec09', category: 'Security Systems', subcategory: 'Barrier', description: 'Boom barrier (parking / gate)', specification: 'Magnetic RFID boom barrier, 3–6m arm, auto', unit: 'nos', rate: 65000, rate_min: 45000, rate_max: 110000, gst_percent: 18 },

  // ─── FIRE SAFETY ─────────────────────────────────────────────
  { id: 'fs01', category: 'Fire Safety', subcategory: 'Detection', description: 'Smoke detector (addressable)', specification: 'Notifier/Honeywell addressable smoke detector', unit: 'nos', rate: 4500, rate_min: 3000, rate_max: 7500, gst_percent: 18 },
  { id: 'fs02', category: 'Fire Safety', subcategory: 'Detection', description: 'Heat detector', specification: 'Rate-of-rise heat detector, conventional, ceiling mount', unit: 'nos', rate: 2800, rate_min: 1800, rate_max: 4500, gst_percent: 18 },
  { id: 'fs03', category: 'Fire Safety', subcategory: 'Detection', description: 'Fire alarm control panel (4 zone)', specification: 'Notifier/Agni 4-zone conventional FACP with batteries', unit: 'nos', rate: 22000, rate_min: 15000, rate_max: 38000, gst_percent: 18 },
  { id: 'fs04', category: 'Fire Safety', subcategory: 'Suppression', description: 'Dry powder extinguisher 4kg', specification: 'ABC dry powder, ISI marked, wall bracket', unit: 'nos', rate: 1800, rate_min: 1200, rate_max: 3200, gst_percent: 18 },
  { id: 'fs05', category: 'Fire Safety', subcategory: 'Suppression', description: 'CO2 extinguisher 4.5kg', specification: 'CO2, server room / kitchen, ISI marked', unit: 'nos', rate: 5500, rate_min: 3800, rate_max: 9500, gst_percent: 18 },
  { id: 'fs06', category: 'Fire Safety', subcategory: 'Suppression', description: 'Fire sprinkler system (per head)', specification: 'Concealed pendent sprinkler, 68°C glass bulb, 1" pipe', unit: 'nos', rate: 3500, rate_min: 2500, rate_max: 5500, gst_percent: 18 },
  { id: 'fs07', category: 'Fire Safety', subcategory: 'Egress', description: 'Emergency exit light', specification: 'LED, 3hr battery backup, self-test function', unit: 'nos', rate: 3200, rate_min: 2000, rate_max: 5500, gst_percent: 18 },
  { id: 'fs08', category: 'Fire Safety', subcategory: 'Egress', description: 'Fire exit signage (illuminated)', specification: 'LED backlit, photoluminescent, wall/ceiling mount', unit: 'nos', rate: 1800, rate_min: 1200, rate_max: 3200, gst_percent: 18 },

  // ─── AV & HOME THEATER ────────────────────────────────────────
  { id: 'av01', category: 'AV & Home Theater', subcategory: 'Display', description: 'LED smart TV 65" 4K', specification: 'Samsung/Sony 65" 4K QLED, wall mounted', unit: 'nos', rate: 85000, rate_min: 55000, rate_max: 150000, gst_percent: 28 },
  { id: 'av02', category: 'AV & Home Theater', subcategory: 'Display', description: 'LED smart TV 85" 4K', specification: 'Samsung/LG 85" 4K OLED/QLED, wall mounted', unit: 'nos', rate: 180000, rate_min: 120000, rate_max: 350000, gst_percent: 28 },
  { id: 'av03', category: 'AV & Home Theater', subcategory: 'Projection', description: 'Home theater projector 4K + screen', specification: 'Epson/Sony 4K laser projector, 150" acoustic screen', unit: 'lot', rate: 280000, rate_min: 150000, rate_max: 600000, gst_percent: 28 },
  { id: 'av04', category: 'AV & Home Theater', subcategory: 'Audio', description: 'Soundbar (Dolby Atmos)', specification: 'Samsung/Sony Dolby Atmos soundbar + subwoofer', unit: 'nos', rate: 35000, rate_min: 18000, rate_max: 85000, gst_percent: 28 },
  { id: 'av05', category: 'AV & Home Theater', subcategory: 'Audio', description: 'Home theater 5.1 speaker system', specification: 'Bowers & Wilkins / Klipsch 5.1 set + AV receiver', unit: 'lot', rate: 180000, rate_min: 80000, rate_max: 500000, gst_percent: 28 },
  { id: 'av06', category: 'AV & Home Theater', subcategory: 'Audio', description: 'In-ceiling speaker pair (per room)', specification: 'Sonos/Klipsch 6.5" in-ceiling, amplifier point', unit: 'nos', rate: 22000, rate_min: 14000, rate_max: 45000, gst_percent: 28 },
  { id: 'av07', category: 'AV & Home Theater', subcategory: 'Networking', description: 'WiFi access point (ceiling-mount)', specification: 'Ubiquiti UniFi / Cisco PoE AP, 802.11ax (Wi-Fi 6)', unit: 'nos', rate: 14000, rate_min: 9000, rate_max: 22000, gst_percent: 18 },
  { id: 'av08', category: 'AV & Home Theater', subcategory: 'Networking', description: 'Network switch (managed, 16-port)', specification: 'Ubiquiti/Cisco 16-port managed PoE switch, rack-mount', unit: 'nos', rate: 18000, rate_min: 12000, rate_max: 35000, gst_percent: 18 },
  { id: 'av09', category: 'AV & Home Theater', subcategory: 'Smart Home', description: 'Smart home hub & controller', specification: 'Lutron / Crestron / Control4 hub, 10-zone system', unit: 'lot', rate: 180000, rate_min: 100000, rate_max: 400000, gst_percent: 18 },

  // ─── GYM & WELLNESS ──────────────────────────────────────────
  { id: 'gym01', category: 'Gym & Wellness', subcategory: 'Equipment', description: 'Treadmill (motorised)', specification: 'NordicTrack/Technogym 3HP motor, auto incline, iFit', unit: 'nos', rate: 65000, rate_min: 35000, rate_max: 150000, gst_percent: 18 },
  { id: 'gym02', category: 'Gym & Wellness', subcategory: 'Equipment', description: 'Multi-gym station', specification: '130kg weight stack, 8 exercise stations, cable system', unit: 'nos', rate: 85000, rate_min: 50000, rate_max: 180000, gst_percent: 18 },
  { id: 'gym03', category: 'Gym & Wellness', subcategory: 'Equipment', description: 'Elliptical cross trainer', specification: 'NordicTrack/Precor, 20" stride, magnetic resistance', unit: 'nos', rate: 55000, rate_min: 30000, rate_max: 120000, gst_percent: 18 },
  { id: 'gym04', category: 'Gym & Wellness', subcategory: 'Equipment', description: 'Free weight dumbbell set (5–50kg)', specification: 'Hex rubber dumbbells, storage rack', unit: 'set', rate: 45000, rate_min: 28000, rate_max: 90000, gst_percent: 18 },
  { id: 'gym05', category: 'Gym & Wellness', subcategory: 'Flooring', description: 'Rubber gym flooring 10mm', specification: 'SBR rubber tile, interlocking, shock-absorbing', unit: 'sqft', rate: 160, rate_min: 110, rate_max: 220, gst_percent: 18 },
  { id: 'gym06', category: 'Gym & Wellness', subcategory: 'Sauna', description: 'Indoor sauna cabin (4-seater)', specification: 'Canadian hemlock wood, 4kW heater, control panel', unit: 'nos', rate: 180000, rate_min: 120000, rate_max: 350000, gst_percent: 18 },
  { id: 'gym07', category: 'Gym & Wellness', subcategory: 'Steam', description: 'Steam shower unit (prefab)', specification: '900×900 prefab cabin, 3kW steam generator, tiles', unit: 'nos', rate: 120000, rate_min: 80000, rate_max: 220000, gst_percent: 18 },
  { id: 'gym08', category: 'Gym & Wellness', subcategory: 'Wellness', description: 'Jacuzzi / spa bath (indoor)', specification: '6-jet acrylic spa bath, 220V, heater, control', unit: 'nos', rate: 180000, rate_min: 110000, rate_max: 380000, gst_percent: 18 },

  // ─── SOLAR & EV ───────────────────────────────────────────────
  { id: 'sol01', category: 'Solar & EV', subcategory: 'Solar PV', description: 'Solar PV system 3kW on-grid', specification: '10×300W mono panels, string inverter, net metering', unit: 'lot', rate: 180000, rate_min: 140000, rate_max: 250000, gst_percent: 5 },
  { id: 'sol02', category: 'Solar & EV', subcategory: 'Solar PV', description: 'Solar PV system 5kW on-grid', specification: '16×325W mono panels, 5kW string inverter, monitoring', unit: 'lot', rate: 290000, rate_min: 230000, rate_max: 400000, gst_percent: 5 },
  { id: 'sol03', category: 'Solar & EV', subcategory: 'Solar PV', description: 'Solar panel supply & install (per Wp)', specification: 'Longi/Waaree mono PERC panels, mounting, MC4 cables', unit: 'Wp', rate: 55, rate_min: 40, rate_max: 75, gst_percent: 5 },
  { id: 'sol04', category: 'Solar & EV', subcategory: 'Solar Thermal', description: 'Solar water heater 200L ETC', specification: 'Racold/Havells ETC 200L, roof mounted, gravity/pressure', unit: 'nos', rate: 28000, rate_min: 20000, rate_max: 45000, gst_percent: 5 },
  { id: 'sol05', category: 'Solar & EV', subcategory: 'Battery', description: 'Home battery storage system 5kWh', specification: 'LiFePO4 battery bank, BMS, 5kW inverter, 10yr life', unit: 'lot', rate: 280000, rate_min: 200000, rate_max: 450000, gst_percent: 5 },
  { id: 'sol06', category: 'Solar & EV', subcategory: 'EV Charging', description: 'EV charging point 7.4kW (AC)', specification: 'AC Type-2, 32A, wall-mounted, 6mm² wiring 10m', unit: 'nos', rate: 35000, rate_min: 25000, rate_max: 55000, gst_percent: 18 },
  { id: 'sol07', category: 'Solar & EV', subcategory: 'EV Charging', description: 'EV charging point 22kW (AC Fast)', specification: '22kW 3-phase AC fast charger, OCPP, CMS integrated', unit: 'nos', rate: 85000, rate_min: 60000, rate_max: 130000, gst_percent: 18 },

  // ─── LANDSCAPING ──────────────────────────────────────────────
  { id: 'land01', category: 'Landscaping', subcategory: 'Lawn', description: 'Natural lawn (Korean grass)', specification: 'Korean/Buffalo grass, topsoil 150mm, watering', unit: 'sqft', rate: 65, rate_min: 45, rate_max: 95, gst_percent: 0 },
  { id: 'land02', category: 'Landscaping', subcategory: 'Lawn', description: 'Artificial turf (premium 35mm)', specification: '35mm pile height, 8-tone realistic, UV stabilised', unit: 'sqft', rate: 280, rate_min: 200, rate_max: 420, gst_percent: 18 },
  { id: 'land03', category: 'Landscaping', subcategory: 'Irrigation', description: 'Drip irrigation system (per 100 sqft)', specification: '4-zone timer, emitters, lateral pipes, filter', unit: 'lot', rate: 18000, rate_min: 12000, rate_max: 30000, gst_percent: 18 },
  { id: 'land04', category: 'Landscaping', subcategory: 'Planting', description: 'Landscape planting (shrubs/trees)', specification: 'Supply & plant, topsoil, mulch, 1yr warranty', unit: 'lot', rate: 120000, rate_min: 60000, rate_max: 300000, gst_percent: 0 },
  { id: 'land05', category: 'Landscaping', subcategory: 'Structure', description: 'Pergola (steel/WPC)', specification: 'MS/WPC pergola 20×12ft, roof slats, powder coated', unit: 'nos', rate: 85000, rate_min: 55000, rate_max: 160000, gst_percent: 18 },
  { id: 'land06', category: 'Landscaping', subcategory: 'Structure', description: 'Gazebo (octagonal 10ft dia)', specification: 'Steel/WPC, fabric canopy, seating provision', unit: 'nos', rate: 120000, rate_min: 80000, rate_max: 220000, gst_percent: 18 },
  { id: 'land07', category: 'Landscaping', subcategory: 'Water Feature', description: 'Garden fountain (wall-mounted)', specification: 'Natural stone / GRC, pump, LED, 1m×0.5m', unit: 'nos', rate: 45000, rate_min: 28000, rate_max: 90000, gst_percent: 18 },
  { id: 'land08', category: 'Landscaping', subcategory: 'Lighting', description: 'Garden / landscape lighting lot', specification: 'Spike lights, up-lights, path lights, 10 points, IP65', unit: 'lot', rate: 65000, rate_min: 40000, rate_max: 120000, gst_percent: 18 },
  { id: 'land09', category: 'Landscaping', subcategory: 'Retaining', description: 'Retaining wall (gabion / brick)', specification: 'Brick masonry or gabion 1m ht, foundation, drainage', unit: 'rft', rate: 3200, rate_min: 2200, rate_max: 5500, gst_percent: 18 },
  { id: 'land10', category: 'Landscaping', subcategory: 'Outdoor Kitchen', description: 'Outdoor kitchen (BBQ + counter)', specification: 'SS countertop, built-in BBQ grill, sink, storage', unit: 'lot', rate: 180000, rate_min: 120000, rate_max: 350000, gst_percent: 18 },

  // ─── APPLIANCES ───────────────────────────────────────────────
  { id: 'app01', category: 'Appliances', subcategory: 'Kitchen', description: 'Refrigerator (French door 400L)', specification: 'LG/Samsung 4-star, inverter, smart connectivity', unit: 'nos', rate: 65000, rate_min: 40000, rate_max: 140000, gst_percent: 18 },
  { id: 'app02', category: 'Appliances', subcategory: 'Kitchen', description: 'Built-in electric oven (60cm)', specification: 'Bosch/Siemens multifunction oven, 66L, 3600W', unit: 'nos', rate: 55000, rate_min: 32000, rate_max: 120000, gst_percent: 18 },
  { id: 'app03', category: 'Appliances', subcategory: 'Kitchen', description: 'Induction hob (90cm 5-zone)', specification: 'Bosch/Siemens 5-zone induction, touch control, CombiZone', unit: 'nos', rate: 65000, rate_min: 38000, rate_max: 140000, gst_percent: 18 },
  { id: 'app04', category: 'Appliances', subcategory: 'Kitchen', description: 'Gas hob (stainless steel 4-burner)', specification: 'Elica/Faber 4-burner SS, auto ignition, heavy pan support', unit: 'nos', rate: 18000, rate_min: 10000, rate_max: 35000, gst_percent: 18 },
  { id: 'app05', category: 'Appliances', subcategory: 'Kitchen', description: 'Dishwasher (built-in 12 place)', specification: 'Bosch/IFB 12 place setting, A++ energy, stainless tub', unit: 'nos', rate: 45000, rate_min: 30000, rate_max: 85000, gst_percent: 18 },
  { id: 'app06', category: 'Appliances', subcategory: 'Kitchen', description: 'Microwave oven (convection 30L)', specification: 'Samsung/IFB 30L convection, grill, solo, touch panel', unit: 'nos', rate: 18000, rate_min: 10000, rate_max: 35000, gst_percent: 28 },
  { id: 'app07', category: 'Appliances', subcategory: 'Kitchen', description: 'Wine cooler (50 bottle)', specification: 'Haier/Samsung 50-bottle dual zone, freestanding', unit: 'nos', rate: 45000, rate_min: 28000, rate_max: 90000, gst_percent: 28 },
  { id: 'app08', category: 'Appliances', subcategory: 'Laundry', description: 'Washing machine (front load 8kg)', specification: 'LG/Samsung 5-star inverter, Wi-Fi, steam care', unit: 'nos', rate: 38000, rate_min: 22000, rate_max: 75000, gst_percent: 18 },
  { id: 'app09', category: 'Appliances', subcategory: 'Laundry', description: 'Washer-dryer combo 9kg', specification: 'LG/Bosch 9kg washer 6kg dryer, heat pump, Wi-Fi', unit: 'nos', rate: 65000, rate_min: 40000, rate_max: 120000, gst_percent: 18 },
  { id: 'app10', category: 'Appliances', subcategory: 'Air Treatment', description: 'Air purifier (HEPA, room 500sqft)', specification: 'Dyson/Philips HEPA + activated carbon, CADR 400+', unit: 'nos', rate: 22000, rate_min: 12000, rate_max: 55000, gst_percent: 18 },

  // ─── MISCELLANEOUS ────────────────────────────────────────────
  { id: 'misc01', category: 'Miscellaneous', subcategory: 'Services', description: 'Overhead water tank 1000L', specification: 'Sintex/Plasto 3-layer anti-bacterial, on stand', unit: 'nos', rate: 20000, rate_min: 14000, rate_max: 32000, gst_percent: 18 },
  { id: 'misc02', category: 'Miscellaneous', subcategory: 'Services', description: 'Underground sump 5000L RCC', specification: 'RCC 150mm walls, waterproofed, manhole cover', unit: 'lot', rate: 95000, rate_min: 65000, rate_max: 160000, gst_percent: 18 },
  { id: 'misc03', category: 'Miscellaneous', subcategory: 'Generator', description: 'Diesel generator set 7.5 KVA', specification: 'Kirloskar/Mahindra 7.5KVA, ATS panel, 100L tank', unit: 'nos', rate: 95000, rate_min: 70000, rate_max: 140000, gst_percent: 18 },
  { id: 'misc04', category: 'Miscellaneous', subcategory: 'Generator', description: 'Home UPS inverter 2kVA', specification: 'Luminous/Microtek 2kVA, 150Ah SMF batteries ×2', unit: 'nos', rate: 35000, rate_min: 24000, rate_max: 55000, gst_percent: 18 },
  { id: 'misc05', category: 'Miscellaneous', subcategory: 'Professional', description: "Architect's / Designer's fee", specification: 'Professional service fee on total project cost', unit: 'lot', rate: 0, rate_min: 0, rate_max: 0, gst_percent: 18 },
  { id: 'misc06', category: 'Miscellaneous', subcategory: 'Professional', description: 'Site supervision charges', specification: 'Per visit or monthly retainer basis', unit: 'lot', rate: 0, rate_min: 0, rate_max: 0, gst_percent: 18 },
  { id: 'misc07', category: 'Miscellaneous', subcategory: 'Cleaning', description: 'Final site cleaning & handover', specification: 'Deep clean all areas, debris removal, polishing', unit: 'lot', rate: 12000, rate_min: 8000, rate_max: 25000, gst_percent: 18 },
  { id: 'misc08', category: 'Miscellaneous', subcategory: 'Waste', description: 'Construction debris disposal', specification: 'Loading + transport + landfill disposal per trip', unit: 'lot', rate: 8000, rate_min: 5000, rate_max: 15000, gst_percent: 18 },
];
